apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: awe-staging
spec:
  template:
    spec:
      containers:
        - name: ui
          env:
            - name: NEXT_PUBLIC_API_URL
              value: /api
            - name: API_PROXY_TARGET
              value: http://api.awe-staging.svc.cluster.local:8000
