apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../staging
patches:
  - path: patch-api-shared.yaml
    target:
      kind: Deployment
      name: api
  - path: patch-worker-hostpath.json
    target:
      group: apps
      version: v1
      kind: Deployment
      name: worker
  - path: patch-rag-retriever-shared.json
    target:
      group: apps
      version: v1
      kind: Deployment
      name: rag-retriever-mcp
  - path: patch-pvc-shared-delete.yaml
    target:
      kind: PersistentVolumeClaim
      name: shared-data
