apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ui
          imagePullPolicy: Always
          env:
            - name: NEXT_PUBLIC_API_URL
              value: /api
            - name: API_PROXY_TARGET
              value: http://api.awe.svc.cluster.local:8000
