apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-qdrant-pv
  namespace: awe
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/awe-qdrant
    type: DirectoryOrCreate
